MOV M8, 7;   N = 7
MOV M1, 1;   CURRENT RESULT OF MULTIPLICATION

; CALCULATE N - 1
PUSH M8;
PUSH -1;
ADD;
POP M7;

; MULTIPLY N (M8) AND RESULT (M1) AND STORE IN M1
PUSH M8;     
PUSH M1;
MUL;
POP M1;

; MOVE N -1 TO M8 AND COMPARE M7 AND 1 IF M7 > 1 THEN REPEAT
MOV M8, M7;
CMP 1, M7;
JNZ -14;

OUTPUT M1